In [147]:
# Libraries

In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [149]:
df = pd.read_csv('Data/british_airways_ready.csv')
pd.set_option('display.max_columns',25)
df.head()

Review_Date  Review_Year  Review_Month  Flown_Date  Flown_Year  Flown_Month  \
0  2024-03-26         2024             3  2024-03-01        2024            3   
1  2024-03-25         2024             3  2024-03-01        2024            3   
2  2024-03-25         2024             3  2024-03-01        2024            3   
3  2024-03-21         2024             3  2024-03-01        2024            3   
4  2024-03-21         2024             3  2024-03-01        2024            3   

    Comment Full_review   Reviewer_Name Reviewer_Country           Origin  \
0  Negative    Negative        R Norton   United Kingdom           Lisbon   
1   Neutral    Positive        Paul Lee   United Kingdom           London   
2  Negative    Negative  Peter Buchanan   United Kingdom           Madrid   
3   Neutral    Negative  Michael Powell   United Kingdom  London Heathrow   
4  Positive    Positive        N Wardan           Canada         Montreal   

                  Destination                          Aircraft  \
0                      London                              A320   
1                       Milan                              A320   
2             London Heathrow                              A320   
3                    Toulouse                              A320   
4  Venice via London Heathrow  Boeing 787-8 /777-200 / A320-200   

      Travel_Type      Seat_Type  Seat_Rating  Cabin_staff_service_Rating  \
0        Business  Economy Class            4                           3   
1  Couple Leisure  Economy Class            5                           5   
2  Couple Leisure  Economy Class            3                           3   
3    Solo Leisure  Economy Class            4                           4   
4  Family Leisure  Economy Class            4                           5   

   Food_Beverages_Rating  Inflight_Rating  Ground_service_Rating  \
0                      2                2                      1   
1                      5                2                      4   
2                      2                2                      3   
3                      2                2                      3   
4                      5                4                      3   

   Value_Rating  Rating Recommended Verified  Target  
0             3       5         YES      YES       0  
1             5       9         YES       NO       0  
2             2       3          NO      YES       0  
3             3       8         YES       NO       0  
4             4       8         YES      YES       0

In [150]:
df2 = df.copy()
df2.head()

Review_Date  Review_Year  Review_Month  Flown_Date  Flown_Year  Flown_Month  \
0  2024-03-26         2024             3  2024-03-01        2024            3   
1  2024-03-25         2024             3  2024-03-01        2024            3   
2  2024-03-25         2024             3  2024-03-01        2024            3   
3  2024-03-21         2024             3  2024-03-01        2024            3   
4  2024-03-21         2024             3  2024-03-01        2024            3   

    Comment Full_review   Reviewer_Name Reviewer_Country           Origin  \
0  Negative    Negative        R Norton   United Kingdom           Lisbon   
1   Neutral    Positive        Paul Lee   United Kingdom           London   
2  Negative    Negative  Peter Buchanan   United Kingdom           Madrid   
3   Neutral    Negative  Michael Powell   United Kingdom  London Heathrow   
4  Positive    Positive        N Wardan           Canada         Montreal   

                  Destination                          Aircraft  \
0                      London                              A320   
1                       Milan                              A320   
2             London Heathrow                              A320   
3                    Toulouse                              A320   
4  Venice via London Heathrow  Boeing 787-8 /777-200 / A320-200   

      Travel_Type      Seat_Type  Seat_Rating  Cabin_staff_service_Rating  \
0        Business  Economy Class            4                           3   
1  Couple Leisure  Economy Class            5                           5   
2  Couple Leisure  Economy Class            3                           3   
3    Solo Leisure  Economy Class            4                           4   
4  Family Leisure  Economy Class            4                           5   

   Food_Beverages_Rating  Inflight_Rating  Ground_service_Rating  \
0                      2                2                      1   
1                      5                2                      4   
2                      2                2                      3   
3                      2                2                      3   
4                      5                4                      3   

   Value_Rating  Rating Recommended Verified  Target  
0             3       5         YES      YES       0  
1             5       9         YES       NO       0  
2             2       3          NO      YES       0  
3             3       8         YES       NO       0  
4             4       8         YES      YES       0

In [151]:
print('Based on Given Data',round((df[df['Flown_Month'].isin([1,2,11,12])].shape[0]/df.shape[0])*100,2),'% People Travelled in Festive Season')

Based on Given Data 32.13 % People Travelled in Festive Season


- Removing unwanted columns
1. Review_Date,Flown_Date,Month,Year is not needed
2. Reviewer_Name 

In [152]:
df.drop(columns=['Flown_Date','Flown_Year','Review_Date','Review_Year','Review_Month','Reviewer_Name'],inplace=True)

## Encoding

In [153]:
df['Flown_Month'].unique() # No Encoding Needed + all Rating columns are already numerical values

array([ 3,  2,  6,  9,  1, 11, 10, 12,  7,  8,  4,  5], dtype=int64)

In [154]:
df['Comment'].unique()

array(['Negative', 'Neutral', 'Positive'], dtype=object)

In [155]:
comment_mapping = {'Negative': -1, 'Neutral': 0, 'Positive': 1}
df['Comment'] = df['Comment'].map(comment_mapping)
df['Comment'].unique()

array([-1,  0,  1], dtype=int64)

In [156]:
df['Full_review'].unique()

array(['Negative', 'Positive', 'Neutral'], dtype=object)

In [157]:
review_mapping = {'Negative': -1, 'Neutral': 0, 'Positive': 1}
df['Full_review'] = df['Full_review'].map(review_mapping)
df['Full_review'].unique()

array([-1,  1,  0], dtype=int64)

In [158]:
df['Reviewer_Country'].unique()

array(['United Kingdom', 'Canada', 'Singapore', 'Belgium', 'Denmark',
       'Australia', 'United States', 'Nigeria', 'Japan', 'Ukraine',
       'Germany', 'Ireland', 'Spain', 'China', 'Ecuador', 'Switzerland',
       'Romania', 'Italy', 'Netherlands', 'France', 'South Africa',
       'Kuwait', 'Iceland', 'Qatar', 'Greece', 'Senegal',
       'United Arab Emirates', 'Cyprus', 'Chile', 'Sweden', 'Hong Kong',
       'Austria', 'India', 'New Zealand', 'Czech Republic', 'Malaysia',
       'Ghana', 'Bermuda', 'Botswana', 'Panama', 'Russian Federation',
       'Philippines', 'Thailand', 'Poland', 'Argentina',
       'Saint Kitts and Nevis', 'Vietnam', 'Norway', 'Jordan', 'Mexico',
       'Taiwan', 'Slovakia', 'Israel', 'South Korea', 'Saudi Arabia',
       'Hungary', 'Brazil', 'Portugal', 'Cayman Islands', 'Costa Rica',
       'Egypt', 'Laos', 'Turkey', 'Indonesia', 'Bahrain',
       'Dominican Republic', 'Bulgaria', 'Luxembourg', 'Finland'],
      dtype=object)

In [159]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Reviewer_Country'] = label_encoder.fit_transform(df['Reviewer_Country'])
df['Reviewer_Country'].unique()

array([66,  9, 54,  4, 16,  1, 67, 42, 33, 64, 22, 30, 58, 12, 18, 60, 49,
       32, 40, 21, 56, 35, 27, 48, 24, 53, 65, 14, 11, 59, 25,  2, 28, 41,
       15, 38, 23,  5,  6, 44, 50, 45, 62, 46,  0, 51, 68, 43, 34, 39, 61,
       55, 31, 57, 52, 26,  7, 47, 10, 13, 19, 36, 63, 29,  3, 17,  8, 37,
       20])

In [160]:
df.columns

Index(['Flown_Month', 'Comment', 'Full_review', 'Reviewer_Country', 'Origin',
       'Destination', 'Aircraft', 'Travel_Type', 'Seat_Type', 'Seat_Rating',
       'Cabin_staff_service_Rating', 'Food_Beverages_Rating',
       'Inflight_Rating', 'Ground_service_Rating', 'Value_Rating', 'Rating',
       'Recommended', 'Verified', 'Target'],
      dtype='object')

In [161]:
df['Origin'].unique()

array(['Lisbon', 'London', 'Madrid', 'London Heathrow', 'Montreal',
       'Paphos', 'Barbados', 'Toronto', 'Copenhagen', 'Los Angeles',
       'Singapore', 'Cyprus', 'Heathrow', 'Sydney', 'Pisa', 'Malaga',
       'Phoenix', 'Austin, TX', 'Athens', 'London Gatwick', 'Boston',
       'Sao Paulo', 'Dusseldorf (DUS)', 'Cairo', 'Dublin', 'Glasgow',
       'Vancouver', 'Rome', 'Gatwick', 'Istanbul', 'Indianapolis',
       'Gran Canaria', 'Belfast City', 'Miami', 'Johannesburg',
       'Palma de Mallorca', 'Zürich', 'Brussels', 'Bucharest',
       'Manchester', 'Seville', 'London Heatrow', 'Anchorage', 'Seattle',
       'Malta', 'San Francisco', 'İstanbul', 'Geneva', 'Porto', 'Catania',
       'Berlin', 'Atlanta', 'Chicago', 'Milan', 'Dallas', 'Prague',
       'San Diego', 'Hamburg', 'Kuwait', 'Frankfurt', 'Mumbai', 'Houston',
       'New York JFK', 'Tenerife', 'Newark', 'Delhi', 'Larnaca',
       'Washington', 'Edinburgh', 'Keflavik', 'Gibraltar', 'Rhodes',
       'Barcelona', 'Inverness', 

In [162]:
df['Origin'].nunique()

292

In [163]:
target_mean_origin = df.groupby('Origin')['Target'].mean()
target_mean_destination = df.groupby('Destination')['Target'].mean()
df['Origin'] = df['Origin'].map(target_mean_origin)
df['Destination'] = df['Destination'].map(target_mean_destination)

In [164]:
df.head()

Flown_Month  Comment  Full_review  Reviewer_Country    Origin  Destination  \
0            3       -1           -1                66  0.500000     0.320293   
1            3        0            1                66  0.307847     0.100000   
2            3       -1           -1                66  0.333333     0.289017   
3            3        0           -1                66  0.257143     0.000000   
4            3        1            1                 9  0.500000     0.000000   

                           Aircraft     Travel_Type      Seat_Type  \
0                              A320        Business  Economy Class   
1                              A320  Couple Leisure  Economy Class   
2                              A320  Couple Leisure  Economy Class   
3                              A320    Solo Leisure  Economy Class   
4  Boeing 787-8 /777-200 / A320-200  Family Leisure  Economy Class   

   Seat_Rating  Cabin_staff_service_Rating  Food_Beverages_Rating  \
0            4                           3                      2   
1            5                           5                      5   
2            3                           3                      2   
3            4                           4                      2   
4            4                           5                      5   

   Inflight_Rating  Ground_service_Rating  Value_Rating  Rating Recommended  \
0                2                      1             3       5         YES   
1                2                      4             5       9         YES   
2                2                      3             2       3          NO   
3                2                      3             3       8         YES   
4                4                      3             4       8         YES   

  Verified  Target  
0      YES       0  
1       NO       0  
2      YES       0  
3       NO       0  
4      YES       0

In [165]:
df['Aircraft'].nunique()

189

In [166]:
target_mean_aircraft = df.groupby('Aircraft')['Target'].mean()
df['Aircraft'] = df['Aircraft'].map(target_mean_aircraft)
df.head()

Flown_Month  Comment  Full_review  Reviewer_Country    Origin  Destination  \
0            3       -1           -1                66  0.500000     0.320293   
1            3        0            1                66  0.307847     0.100000   
2            3       -1           -1                66  0.333333     0.289017   
3            3        0           -1                66  0.257143     0.000000   
4            3        1            1                 9  0.500000     0.000000   

   Aircraft     Travel_Type      Seat_Type  Seat_Rating  \
0  0.303769        Business  Economy Class            4   
1  0.303769  Couple Leisure  Economy Class            5   
2  0.303769  Couple Leisure  Economy Class            3   
3  0.303769    Solo Leisure  Economy Class            4   
4  0.000000  Family Leisure  Economy Class            4   

   Cabin_staff_service_Rating  Food_Beverages_Rating  Inflight_Rating  \
0                           3                      2                2   
1                           5                      5                2   
2                           3                      2                2   
3                           4                      2                2   
4                           5                      5                4   

   Ground_service_Rating  Value_Rating  Rating Recommended Verified  Target  
0                      1             3       5         YES      YES       0  
1                      4             5       9         YES       NO       0  
2                      3             2       3          NO      YES       0  
3                      3             3       8         YES       NO       0  
4                      3             4       8         YES      YES       0

In [167]:
df['Travel_Type'].unique()

array(['Business', 'Couple Leisure', 'Solo Leisure', 'Family Leisure'],
      dtype=object)

In [168]:
travel_mapping = {'Business': 1, 'Couple Leisure': 2, 'Solo Leisure': 3,'Family Leisure':4}
df['Travel_Type'] = df['Travel_Type'].map(travel_mapping)
df['Travel_Type'].unique()

array([1, 2, 3, 4], dtype=int64)

In [169]:
df['Seat_Type'].unique()

array(['Economy Class', 'Business Class', 'First Class',
       'Premium Economy'], dtype=object)

In [170]:
seat_mapping = {'Economy Class': 1, 'Business Class': 2, 'First Class': 3,'Premium Economy':4}
df['Seat_Type'] = df['Seat_Type'].map(seat_mapping)
df['Seat_Type'].unique()

array([1, 2, 3, 4], dtype=int64)

In [171]:
df['Recommended'].unique()

array(['YES', 'NO'], dtype=object)

In [172]:
recommend_mapping = {'YES': 1, 'NO': 0}
df['Recommended'] = df['Recommended'].map(recommend_mapping)
df['Recommended'].unique()

array([1, 0], dtype=int64)

In [173]:
df['Verified'].unique()

array(['YES', 'NO'], dtype=object)

In [174]:
recommend_mapping = {'YES': 1, 'NO': 0}
df['Verified'] = df['Verified'].map(recommend_mapping)
df['Verified'].unique()

array([1, 0], dtype=int64)

## Standardization

In [175]:
df.head()

Flown_Month  Comment  Full_review  Reviewer_Country    Origin  Destination  \
0            3       -1           -1                66  0.500000     0.320293   
1            3        0            1                66  0.307847     0.100000   
2            3       -1           -1                66  0.333333     0.289017   
3            3        0           -1                66  0.257143     0.000000   
4            3        1            1                 9  0.500000     0.000000   

   Aircraft  Travel_Type  Seat_Type  Seat_Rating  Cabin_staff_service_Rating  \
0  0.303769            1          1            4                           3   
1  0.303769            2          1            5                           5   
2  0.303769            2          1            3                           3   
3  0.303769            3          1            4                           4   
4  0.000000            4          1            4                           5   

   Food_Beverages_Rating  Inflight_Rating  Ground_service_Rating  \
0                      2                2                      1   
1                      5                2                      4   
2                      2                2                      3   
3                      2                2                      3   
4                      5                4                      3   

   Value_Rating  Rating  Recommended  Verified  Target  
0             3       5            1         1       0  
1             5       9            1         0       0  
2             2       3            0         1       0  
3             3       8            1         0       0  
4             4       8            1         1       0

In [176]:
df.dtypes

Flown_Month                     int64
Comment                         int64
Full_review                     int64
Reviewer_Country                int32
Origin                        float64
Destination                   float64
Aircraft                      float64
Travel_Type                     int64
Seat_Type                       int64
Seat_Rating                     int64
Cabin_staff_service_Rating      int64
Food_Beverages_Rating           int64
Inflight_Rating                 int64
Ground_service_Rating           int64
Value_Rating                    int64
Rating                          int64
Recommended                     int64
Verified                        int64
Target                          int64
dtype: object

In [177]:
df.isnull().sum()

Flown_Month                   0
Comment                       0
Full_review                   0
Reviewer_Country              0
Origin                        0
Destination                   0
Aircraft                      0
Travel_Type                   0
Seat_Type                     0
Seat_Rating                   0
Cabin_staff_service_Rating    0
Food_Beverages_Rating         0
Inflight_Rating               0
Ground_service_Rating         0
Value_Rating                  0
Rating                        0
Recommended                   0
Verified                      0
Target                        0
dtype: int64

In [178]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [179]:
numerical_cols = df.select_dtypes(include=['int', 'float']).columns.drop('Target') # Except Target Column
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [180]:
df.head()

Flown_Month   Comment  Full_review  Reviewer_Country    Origin  \
0    -1.105474 -1.206304    -1.059467          0.488297  1.137115   
1    -1.105474  0.098051     0.958808          0.488297 -0.085513   
2    -1.105474 -1.206304    -1.059467          0.488297  0.076651   
3    -1.105474  0.098051    -1.059467          0.488297 -0.408133   
4    -1.105474  1.402405     0.958808         -2.396004  1.137115   

   Destination  Aircraft  Travel_Type  Seat_Type  Seat_Rating  \
0    -0.004927 -0.137283    -1.383261   -0.73575     1.046767   
1    -1.097739 -0.137283    -0.357126   -0.73575     1.831487   
2    -0.160078 -0.137283    -0.357126   -0.73575     0.262046   
3    -1.593810 -0.137283     0.669009   -0.73575     1.046767   
4    -1.593810 -2.517932     1.695144   -0.73575     1.046767   

   Cabin_staff_service_Rating  Food_Beverages_Rating  Inflight_Rating  \
0                   -0.040100              -0.311023        -0.218307   
1                    1.355590               2.053263        -0.218307   
2                   -0.040100              -0.311023        -0.218307   
3                    0.657745              -0.311023        -0.218307   
4                    1.355590               2.053263         2.031430   

   Ground_service_Rating  Value_Rating    Rating  Recommended  Verified  \
0              -1.195536      0.424004  0.294948     1.452236  1.231038   
1               0.935938      1.862652  1.638908     1.452236 -0.812323   
2               0.225447     -0.295321 -0.377033    -0.688593  1.231038   
3               0.225447      0.424004  1.302918     1.452236 -0.812323   
4               0.225447      1.143328  1.302918     1.452236  1.231038   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

## Splitting

In [181]:
from sklearn.model_selection import train_test_split
X = df.drop('Target', axis=1)
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Model

In [182]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [183]:
feature_names = X.columns
coefficients = model.coef_[0]
feature_importance = dict(zip(feature_names, coefficients))
sorted_feature_importance = sorted(feature_importance.items(), key=lambda x: abs(x[1]), reverse=True)
for feature, coef in sorted_feature_importance:
    print(f"{feature}: {coef}")

Destination: 1.28068699732675
Origin: 0.953669866143122
Aircraft: 0.7068781029660304
Verified: 0.28288261684928473
Cabin_staff_service_Rating: 0.15974984212285379
Inflight_Rating: -0.14342846740118645
Full_review: -0.11723924711363604
Value_Rating: 0.11045479857468875
Food_Beverages_Rating: -0.10895236216548175
Seat_Type: -0.10540593355512136
Seat_Rating: 0.07091815062086342
Recommended: 0.047830839873640126
Flown_Month: 0.0429275490797547
Comment: -0.033521404535358644
Ground_service_Rating: 0.03259162801621113
Reviewer_Country: 0.03203275371712728
Travel_Type: 0.009725329545814107
Rating: -0.00435398571612956


In [184]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.7527075812274369


In [185]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, roc_curve
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
y_prob = model.predict_proba(X_test)[:, 1]
auc_roc = roc_auc_score(y_test, y_prob)
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("AUC-ROC:", auc_roc)

Precision: 0.5882352941176471
Recall: 0.4968944099378882
F1-score: 0.5387205387205388
AUC-ROC: 0.8009577544924374


In [186]:
X_test.shape

(554, 18)

In [187]:
X_test['Ouput'] = y_pred

In [188]:
X_test.index

Index([1378,  839, 2163, 2618,  927,  450,  368, 1135, 1756,  296,
       ...
        157, 1640, 2326,  238, 2603,  874, 2031,  100,  315, 1740],
      dtype='int64', length=554)

In [189]:
cross_check = df2.iloc[X_test.index]

In [190]:
cross_check['Output'] = y_pred

C:\Users\LOKESH\AppData\Local\Temp\ipykernel_12388\745167614.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cross_check['Output'] = y_pred


In [191]:
cross_check

Review_Date  Review_Year  Review_Month  Flown_Date  Flown_Year  \
1378  2017-10-21         2017            10  2017-09-01        2017   
839   2019-06-27         2019             6  2019-06-01        2019   
2163  2016-05-19         2016             5  2016-05-01        2016   
2618  2015-09-01         2015             9  2015-08-01        2015   
927   2019-03-03         2019             3  2019-02-01        2019   
...          ...          ...           ...         ...         ...   
874   2019-05-16         2019             5  2019-05-01        2019   
2031  2016-09-15         2016             9  2016-09-01        2016   
100   2023-10-07         2023            10  2023-10-01        2023   
315   2022-12-19         2022            12  2022-11-01        2022   
1740  2017-02-22         2017             2  2017-02-01        2017   

      Flown_Month   Comment Full_review    Reviewer_Name Reviewer_Country  \
1378            9  Positive    Positive   Anthony Geddes        Australia   
839             6  Positive    Positive          M Beale   United Kingdom   
2163            5   Neutral    Positive           J Hugo   United Kingdom   
2618            8   Neutral    Positive       Chris Hall        Australia   
927             2  Positive    Positive      Sharon Baun   United Kingdom   
...           ...       ...         ...              ...              ...   
874             5   Neutral    Positive    Manuel Vieira   United Kingdom   
2031            9  Negative    Positive      T Giannugni   United Kingdom   
100            10  Positive    Positive   Peter Costello   United Kingdom   
315            11  Negative    Positive  Richard Cowling   United Kingdom   
1740            2   Neutral    Negative       T Davidson   United Kingdom   

               Origin     Destination  ...        Seat_Type Seat_Rating  \
1378      London City       Edinburgh  ...    Economy Class           5   
839   London Heathrow         Larnaca  ...   Business Class           4   
2163     New York JFK             LHR  ...    Economy Class           4   
2618          Calgary          London  ...    Economy Class           5   
927          Heathrow        New York  ...    Economy Class           4   
...               ...             ...  ...              ...         ...   
874            London        Aberdeen  ...    Economy Class           2   
2031           Naples  London Gatwick  ...    Economy Class           2   
100            London    New York JFK  ...      First Class           5   
315    London Gatwick          Cancun  ...  Premium Economy           4   
1740  London Heathrow         Chicago  ...      First Class           1   

     Cabin_staff_service_Rating  Food_Beverages_Rating  Inflight_Rating  \
1378                          4                      4                2   
839                           5                      5                2   
2163                          4                      3                2   
2618                          5                      2                2   
927                           5                      5                3   
...                         ...                    ...              ...   
874                           2                      2                2   
2031                          3                      1                2   
100                           5                      5                4   
315                           1                      1                3   
1740                          1                      1                1   

      Ground_service_Rating  Value_Rating  Rating  Recommended  Verified  \
1378                      4             4       9          YES        NO   
839                       5             5      10          YES       YES   
2163                      5             3       6          YES        NO   
2618                      4             4       7          YES        NO   
927                       5             5    